# Generated by Django 3.2.5 on 2022-11-27 14:22

from django.db import migrations, models
import futoalumni.image_check


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('othernames', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('year_of_graduation', models.CharField(max_length=4)),
                ('discipline', models.CharField(max_length=30)),
                ('passport', models.ImageField(upload_to=futoalumni.image_check.item_files_directory)),
                ('subscribed', models.BooleanField(default=False)),
            ],
        ),
    ]
