# Generated by Django 3.2.5 on 2022-11-27 22:19

from django.db import migrations, models
import futoalumni.image_check


class Migration(migrations.Migration):

    dependencies = [
        ('futoalumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nature_of_biz', models.TextField()),
                ('bussines_phote', models.ImageField(upload_to=futoalumni.image_check.business_files_directory)),
            ],
        ),
    ]
