# Generated by Django 3.2.5 on 2022-11-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futoalumni', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='Alumni',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futoalumni.alumni'),
        ),
    ]
