# Generated by Django 3.2.5 on 2022-11-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futoalumni', '0003_business_alumni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Alumni',
            new_name='alumni',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bussines_phote',
            new_name='bussines_photo',
        ),
    ]
