# Generated by Django 3.2.5 on 2022-11-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futoalumni', '0004_auto_20221127_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='company_name',
        ),
    ]
